### ISSUE TITLE
ImportError after update to v0.2.17

### ISSUE THREAD

**Issue by jrappen** [randy3k/Terminus#80]
```text
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "~/Library/Application Support/Sublime Text 3/Packages/Terminus/main.py", line 6, in <module>
    from .terminus.commands import (
ImportError: cannot import name TerminusViewEventListener
```

**Comment by randy3k** [comment]
Restarting Sublime?

**Comment by jrappen** [comment]
Nope, after Package Control updating Terminus. Same with v0.2.20:

```text
Package Control: Upgraded Terminus to 0.2.20
ignored packages updated to: ["Vintage"]
reloading plugin Terminus.main
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "~/Library/Application Support/Sublime Text 3/Packages/Terminus/main.py", line 6, in <module>
    from .terminus.commands import (
ImportError: cannot import name TerminusInitializeCommand
```

**Comment by randy3k** [comment]
Try restarting again.

**Comment by randy3k** [comment]
Ya, basically we need to use a reloader to reload the whole package when PC upgrades Terminus.

**Comment by randy3k** [comment]
v0.2.21 added a reloader
